import "@/styles/globals.css";

import { Inter as FontSans } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { HydrateClient } from "@/trpc/server";

import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fontSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <HydrateClient>
            <Providers>
              {children}
              <Toaster richColors closeButton />
            </Providers>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
